In [1]:
import numpy as np

In [28]:
def power(a, error_max):
    error = 10000
    iter_max = 100
    iter = 0
    row_size = a.shape[0]
    x = np.ones(row_size)
    eigen_max0 = 10
    while error > error_max:
        b = np.dot(a,x)
        index = np.argmax(abs(b)) # argmax - 주소
        eigen_max = b[index]
        x = b/eigen_max
        error = abs((eigen_max - eigen_max0)/eigen_max0) * 100
        eigen_max0 = eigen_max
        print('iter:'.format(iter),eigen_max,x)
        ++iter
    return eigen_max,x,iter

a = np.array([[40,-20,0],[-20,40,-20],[0,-20,40]])
error_max = 0.0001
result_a,result_b,iter = power(a,error_max)
# np.linalg.eig(a) => 고유값 계산 
e,f = np.linalg.eig(a)
print(e,f)

iter: 20.0 [1. 0. 1.]
iter: 40.0 [ 1. -1.  1.]
iter: -80.0 [-0.75  1.   -0.75]
iter: 70.0 [-0.71428571  1.         -0.71428571]
iter: 68.57142857142857 [-0.70833333  1.         -0.70833333]
iter: 68.33333333333333 [-0.70731707  1.         -0.70731707]
iter: 68.29268292682927 [-0.70714286  1.         -0.70714286]
iter: 68.28571428571429 [-0.70711297  1.         -0.70711297]
iter: 68.28451882845188 [-0.70710784  1.         -0.70710784]
iter: 68.2843137254902 [-0.70710696  1.         -0.70710696]
iter: 68.28427853553482 [-0.70710681  1.         -0.70710681]
[68.28427125 40.         11.71572875] [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01 -1.28295502e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [29]:
#위 방법은  고유값중 최대값을 구하는데 최소값은 어떻게 구하나?
#A의 역행렬을 최대값에 대입하고 , 그렇게 해서 나온 람다의 역수.

In [23]:
a_inv = np.linalg.inv(a)

In [32]:
result3_a,result3_b,c= power(a_inv,error_max)

iter: 0.1 [0.75 1.   0.75]
iter: 0.08750000000000001 [0.71428571 1.         0.71428571]
iter: 0.0857142857142857 [0.70833333 1.         0.70833333]
iter: 0.08541666666666668 [0.70731707 1.         0.70731707]
iter: 0.08536585365853659 [0.70714286 1.         0.70714286]
iter: 0.08535714285714285 [0.70711297 1.         0.70711297]
iter: 0.08535564853556486 [0.70710784 1.         0.70710784]
iter: 0.08535539215686275 [0.70710696 1.         0.70710696]
iter: 0.08535534816941852 [0.70710681 1.         0.70710681]


In [21]:
inv_a = 1/result3_a
print(inv_a)
print(result3_b)

11.715727502102608
[0.70710681 1.         0.70710681]


In [22]:
#eig로 해를 구할 시 , 고유값은 같지만 고유벡터는 다르게 나올 가능성 
#하지만 비제차의 고유값 문제에서 , 고유벡터는 실수배라도 상관이 없음, 어차피 해는 무한

In [ ]:
#주의할 것 : np.linalg.eig()는 람다 * [[a,b,c],[d,e,f],[g,h,i]]